// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/fighter/[name].ts";
import * as $2 from "./routes/fighter/index.ts";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/fighter/[name].ts": $1,
    "./routes/fighter/index.ts": $2,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
